name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/craftology-labs-svelte/ # Replace with your project path
          git pull origin main    # Adjust branch as necessary
          yarn install
          yarn build
          pm2 restart index
        EOF